@startuml
'https://plantuml.com/component-diagram

actor User

package "Presentation Layer" {
  component "CampaignController" as CC
}

package "Business Layer" {
  component "HeroService" as HS
  component "CampaignService" as CS
  component "PartyService" as PS
}

package "Persistence Layer" {
  component "CampaignRepository" as CR
  component "HeroRepository" as HR
  component "PartyRepository" as PR
}

database "MySQL Database" as DB

' === Connections ===

User --> CC

CC --> CS

CS --> HS
CS --> PS
CS --> CR

HS --> HR
PS --> PR

CR --> DB
HR --> DB
PR --> DB


@enduml