@startuml
'https://plantuml.com/class-diagram

title PvP Battle - Observer Pattern

interface Observer {
    + update(message : String)
}

interface Subject {
    + attach(observer : Observer)
    + detach(observer : Observer)
    + notifyObservers()
}

class PvPInvitation implements Subject
class User implements Observer

PvPInvitation --> Observer

@enduml