@startuml
title Use Case 6 - Continue Incomplete PvE Campaign (Updated)

skinparam responseMessageBelowArrow true

autonumber

actor User
boundary CampaignController
control ICampaignService
control ICampaignProgressService
control IInventoryService
database CampaignRepository

User -> CampaignController : Get /campaign
activate CampaignController
CampaignController -> ICampaignService: getActiveCampaign(username)
activate ICampaignService
ICampaignService -> CampaignRepository: findActiveCampaignByUsername(username)
activate CampaignRepository

CampaignRepository --> ICampaignService: active campaign
deactivate CampaignRepository
ICampaignService --> CampaignController: campaign
deactivate ICampaignService

CampaignController -> ICampaignProgressService: getCampaignViewData(username)
activate ICampaignProgressService
ICampaignProgressService --> CampaignController: CampaignViewInfo(campaignId, currentRoom, gold, heroes)
deactivate ICampaignProgressService

CampaignController -> IInventoryService: getPartyInventoryItems(campaignId)
activate IInventoryService
IInventoryService --> CampaignController: List<items>
deactivate IInventoryService

CampaignController --> User: Display campaign page
deactivate CampaignController

@enduml