@startuml

autonumber

skinparam responseMessageBelowArrow true

title Send a PvP Battle Invitation

actor User1

boundary PvPController
control IPvPService
database UserRepository
database PvPInvitationRepository
control IBattleService
boundary BattleController
actor User2

== Send Invitation ==
User1 -> PvPController: Post /invite
activate PvPController
PvPController -> IPvPService: createInvitation(username, enemyUsername)
activate IPvPService
IPvPService -> UserRepository: findByUsername(enemyUsername)
activate UserRepository

alt Player Does Not Exist
    UserRepository --> IPvPService: null
    IPvPService --> PvPController: error("User not found")

else Player Found
    UserRepository --> IPvPService: enemyUser
    deactivate UserRepository

    IPvPService -> IPvPService: Check if each user has a saved party

    alt Either User Has No Saved Party
        IPvPService --> PvPController: error("No saved parties")

    else Both Have a Saved Party
        IPvPService -> PvPInvitationRepository: save(invitation)
        deactivate IPvPService

    end

end

PvPController --> User1: Invitation Sent
deactivate PvPController

== Accept Invitation ==
User2 -> PvPController: Post /accept/{inviteId}
activate PvPController

PvPController -> IPvPService: acceptInvitation(inviteId)
activate IPvPService

IPvPService -> IPvPService: Update invitation status to accepted
IPvPService -> PvPInvitationRepository: save(invitation)
deactivate IPvPService

PvPController -> User2: redirect /pvp/select-party
User2 --> PvPController: selected party
PvPController -> User1: redirect /pvp/select-party
User1 --> PvPController: selected party

PvPController -> IBattleService: initializePvPBattle(senderPartyId, receiverPartyId, inviteId)
deactivate IBattleService
PvPController --> User2: redirect /battle
deactivate PvPController

==Battle Result==
User2 -> BattleController: Get /result
activate BattleController
BattleController -> IBattleService: updatePvPResult(battleState)
activate IBattleService
IBattleService -> IBattleService: Increment winner wins by one and increment loser losses by one
IBattleService -> UserRepository: save(user) for both users

IBattleService --> BattleController: Updated battle state
deactivate IBattleService
BattleController --> User2: Display Battle Result

@enduml